import type { Metadata } from "next";
import "./globals.css";
import ConditionalHeader from "@/components/ConditionalHeader";
import { SpecialitiesProvider } from "@/context/SpecialitiesContext";
import { DoctorsProvider } from "@/context/DoctorsContext";

export const metadata: Metadata = {
  title: "MediciCol - Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConditionalHeader />
          <SpecialitiesProvider>
      
        {children}
        </SpecialitiesProvider>
      </body>
    </html>
  );
}
